services:
  - type: web
    name: cooksphere-api
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: web
    name: cooksphere-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://cooksphere-api.onrender.com
